CREATE TABLE banner
(
ID INT(11) NOT NULL AUTO_INCREMENT,
PLACE_NAME VARCHAR(100) NOT NULL,
PLACE_ADDR VARCHAR(255) NOT NULL,
PLACE_TEL VARCHAR(20),
PLACE_CLOSEDATE VARCHAR(255),
COUNT INT(11) NOT NULL,
PRIMARY KEY(ID)
);